### ISSUE TITLE
Can't install from ssh repos

### ISSUE THREAD

**Issue by dcdanko** [dcdanko/ModuleUltra#4]
See Issue MetaSUB/MetaSUB_CAP#27

**Comment by dcdanko** [comment]
@kohei-108 I am not able to replicate this error on my machine but it could be an authentication issue. Do you have ssh keys set up for github?

**Comment by kohei-108** [comment]
I have ssh keys set up for github, but I can't install it.
I ran the following commands.
```
moduleultra install https://github.com/MetaSUB/MetaSUB_CAP
moduleultra install https://github.com/MetaSUB/MetaSUB_QC_Pipeline
```

**Comment by dcdanko** [comment]
What is the error message, if any?

If there is no error message can you show me the contents of `~/.module_ultra_config/installed_pipelines/`
